name: x11
version: 0.0.0-dev.2

description:
  A native Dart implementation of the X window system protocol, version 11 (X11).

homepage: https://github.com/robert-ancell/x11.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
